management:
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: "*"

resilience4j:
    circuitbreaker:
        instances:
            cfApi:
                registerHealthIndicator: true
            concourseService:
                registerHealthIndicator: true
            ollamaService:
                registerHealthIndicator: true
            vaultService:
                registerHealthIndicator: true

spring:
    application:
        name: remix-gateway
    cloud:
        gateway:
            httpclient:
              ssl:
                useInsecureTrustManager: true
            routes:
                - id: cf-api
                  uri: https://korifi-api-svc.korifi.svc.cluster.local:443
                  predicates:
                    - Host=cf-api.apps-127-0-0-1.nip.io
                  filters:
                    - name: CircuitBreaker
                      args:
                        name: cfApi
                        fallbackUri: forward:/cfApi-fallback
                - id: concourse
                  uri: http://concourse-web.concourse.svc.cluster.local:8080
                  predicates:
                      - Host=concourse.apps-127-0-0-1.nip.io
                  filters:
                      - name: CircuitBreaker
                        args:
                            name: concourseService
                            fallbackUri: forward:/concourse-fallback
                - id: ollama
                  uri: http://ollama.ollama.svc.cluster.local:11434
                  predicates:
                    - Host=ollama.apps-127-0-0-1.nip.io
                  filters:
                    - name: CircuitBreaker
                      args:
                        name: ollamaService
                        fallbackUri: forward:/ollama-fallback
                - id: vault
                  uri: http://vault.vault.svc.cluster.local:8200
                  predicates:
                      - Host=vault.apps-127-0-0-1.nip.io
                  filters:
                      - name: CircuitBreaker
                        args:
                            name: vaultService
                            fallbackUri: forward:/vault-fallback
    threads:
        virtual:
            enabled: true
